services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]


  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=wahlanalyse'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
